### ISSUE TITLE
Transfer ownership on Chef Supermarket?

### ISSUE THREAD

**Issue by mthssdrbrg** [Webtrends/kafka#8]
Heya, not really sure if this is the best way to get in contact, but figured I'd give it a try.

I maintain a `kafka` cookbook (that in fact was based on this one way-back-when :)), and [some users have reached out wondering](https://github.com/mthssdrbrg/kafka-cookbook/issues/93) if it would be possible to transfer the ownership of the `kafka` cookbook that's present on [Supermarket](https://supermarket.chef.io/cookbooks/kafka) (as it's marked as deprecated)?
The thought is then to have version `>= 2` be the "new" version while `< 2` being the deprecated one. I've seen this done for gems on [rubygems.org](https://rubygems.org) and haven't personally encountered any problems with that.

Is this something that would be possible? /cc @tas50

**Comment by tas50** [comment]
@mthssdrbrg I've transferred it to your supermarket account.

**Comment by mthssdrbrg** [comment]
@tas50 thanks a lot :).
